services:
  - type: web
    name: portfolio-jeet
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: EMAIL
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true 